import { AIAnalysis } from '@/types';
import { sleep } from '@/lib/utils';

export async function generateAISummary(
  fileName: string,
  fileContent?: string
): Promise<AIAnalysis> {
  // TODO: integrate Gemini / OpenAI API
  // const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_API_KEY!);
  // const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
  // const result = await model.generateContent(`Analyze this study document: ${fileContent}`);
  // return parseAIResponse(result.response.text());

  // Placeholder until AI integration is wired up
  await sleep(1000);
  return {
    summary: `AI-generated summary for "${fileName}" will appear here once the AI service is configured.`,
    keyPoints: [],
    difficulty: 'Intermediate',
    estimatedReadTime: 0,
    topics: [],
  };
}

export async function generateNoteSummaryFromTitle(title: string): Promise<string> {
  // TODO: replace with real AI call
  await sleep(500);
  return `Summary for "${title}" will be generated by AI once the service is configured.`;
}

export async function chatWithNote(
  noteTitle: string,
  question: string
): Promise<string> {
  // TODO: replace with real AI call using note content as context
  await sleep(500);
  return `AI chat for "${noteTitle}" will be available once the AI service is configured.`;
}
